=== AimWhy/browser-style/ui/data-entry/data/product-schema.json
{
	"$schema": "https://json-schema.org/draft/2019-09/schema",
	"$id": "http://example.com/example.json",
	"type": "object",
	"default": {},
	"required": [
		"id",
		"name",
		"description",
		"product_type_id",
		"condition",
		"published",
		"searchable",
		"sku",
		"created_at",
		"last_modified_at",
		"attributes",
		"price",
		"vendor",
		"channels"
	],
	"render": {
		"toolbar": [
			{
				"label": "Delete",
				"attributes": [
					{ "class": "bg-error --light fs-xs" }
				]
			},
			{
				"label": "Duplicate",
				"attributes": [
					{ "class": "fs-xs" }
				]
			},
			{
				"label": "Update",
				"attributes": [
					{ "class": "bg-success --light fs-xs" }
				]
			}
		]
	},
	"properties": {
		"id": {
			"type": "integer",
			"default": 0,
			"title": "Product ID",
			"render": {
				"method": "input",
				"attributes": [
					{ "disabled": "disabled" },
					{ "name": "id" },
					{ "type": "number" }
				]
			}
		},
		"product_type_id": {
			"type": "integer",
			"default": 0,
			"title": "Product Type",
			"render": {
				"method": "select",
				"options": [
					{ "label": "Book", "value": 1 },
					{ "label": "Comic", "value": 2 },
					{ "label": "Figure", "value": 3 },
					{ "label": "Film", "value": 4 },
					{ "label": "Game", "value": 5 }
				
				],
				"attributes": [
					{ "name": "product_type_id" }
				]
			}
		},
		"name": {
			"type": "string",
			"default": "",
			"title": "Name",
			"render": {
				"method": "input",
				"attributes": [
					{ "placeholder": "Enter product name" },
					{ "name": "name" },
					{ "type": "text" }
				]
			}
		},
		"description": {
			"type": "string",
			"default": "",
			"title": "Description",
			"render": {
				"method": "richtext",
				"attributes": [
					{ "name": "description" },
					{ "toolbar": "h1,h2,h3|b,i,u,s|sub,sup|ol,ul,hr|img|link,unlink" }
				]
			}
		},
		
		"condition": {
			"type": "integer",
			"default": 0,
			"title": "Condition",
			"render": {
				"method": "select",
				"options": [
					{ "label": "New", "value": 1 },
					{ "label": "Used", "value": 2 },
					{ "label": "Refurbished", "value": 3 }
				],
				"attributes": [
					{ "name": "condition" }
				]
			}
		},
		"published": {
			"type": "boolean",
			"default": false,
			"title": "Published",
			"render": {
				"method": "input",
				"attributes": [
					{ "name": "published" },
					{ "type": "checkbox" }
				]
			}
		},
		"searchable": {
			"type": "boolean",
			"default": true,
			"title": "Searchable",
			"render": {
				"method": "input",
				"attributes": [
					{ "name": "searchable" },
					{ "type": "checkbox" }
				]
			}
		},
		"sku": {
			"type": "string",
			"default": "",
			"title": "SKU",
			"render": {
				"method": "input",
				"attributes": [
					{ "placeholder": "Enter SKU" },
					{ "name": "sku" },
					{ "type": "text" }
				]
			}
		},
		"created_at": {
			"type": "string",
			"default": "",
			"title": "Created At",
			"render": {
				"method": "input",
				"attributes": [
					{ "disabled": "disabled" },
					{ "type": "datetime-local" }
				]
			}
		},
		"last_modified_at": {
			"type": "string",
			"default": "",
			"title": "Modified At",
			"render": {
				"method": "input",
				"attributes": [
					{ "disabled": "disabled" },
					{ "type": "datetime-local" }
				]
			}
		},
		"attributes": {
			"type": "array",
			"default": [],
			"title": "Attributes",
			"render": {
				"method": "checklist",
				"attributes": [
					{ "name": "attributes" },
					{ "part": "checklist" }
				],
				"entry": {
					"id": "add_attribute",
					"label": "Add attribute",
					"name": "new_attribute",
					"schema": {
						"type": "object",
						"properties": {
							"attr_label": {
								"title": "Label",
								"type": "string",
								"render": {
									"method": "input",
									"attributes": [
										{ "name": "attr_label" },
										{ "type": "text" },
										{ "placeholder": "Enter label" },
										{ "required": "required" }
									]
								}
							},
							"attr_type": {
								"title": "Type",
								"type": "string",
								"render": {
									"method": "input",
									"attributes": [
										{ "name": "attr_type" },
										{ "type": "text" },
										{ "placeholder": "Enter type" },
										{ "required": "required" }
									]
								}
							},
							"attr_value": {
								"title": "Value",
								"type": "number",
								"render": {
									"method": "input",
									"attributes": [
										{ "name": "attr_value" },
										{ "type": "number" },
										{ "placeholder": "Enter value" },
										{ "required": "required" }
									]
								}
							}
						}
					}
				}
			},
			"items": {
				"type": "object",
				"required": [
					"attr_label",
					"attr_type",
					"attr_value"
				],
				"properties": {
					"attr_label": {
						"type": "string",
						"property": "label"
					},
					"attr_type": {
						"type": "string",
						"property": "type"
					},
					"attr_value": {
						"type": "integer",
						"property": "value",
						"render": {
							"method": "input",
							"attributes": [
								{ "checked": "checked" },
								{ "name": "attribute" },
								{ "class": "bg-gray --fs-lg --cross" },
								{ "type": "checkbox" }
							]
						}
					}
				}
			}
		},
		"price": {
			"type": "array",
			"default": [],
			"title": "Prices",
			"render": {
				"method": "details",
				"summary": "currency_code",
				"label": "value",
				"attributes": [
					{ "name": "price" }
				]
			},
			"items": {
				"type": "object",
				"required": [
					"price_id",
					"currency_code",
					"discount",
					"is_msrp",
					"valid_from",
					"value"
				],
				"properties": {
					"price_id": {
						"type": "integer",
						"render": {
							"method": "input",
							"attributes": [
								{ "name": "price_id" },
								{ "type": "hidden" }
							]
						}
					},
					"currency_code": {
						"type": "string",
						"title": "Currency",
						"render": {
							"method": "input",
							"attributes": [
								{ "disabled": "disabled" },
								{ "name": "currency_code" },
								{ "type": "text" }
							]
						}
					},
					"discount": {
						"type": "boolean",
						"title": "Discount",
						"render": {
							"method": "input",
							"attributes": [
								{ "name": "discount" },
								{ "type": "checkbox" }
							]
						}
					},
					"is_msrp": {
						"type": "boolean",
						"title": "MSRP",
						"render": {
							"method": "input",
							"attributes": [
								{ "name": "is_msrp" },
								{ "type": "checkbox" }
							]
						}
					},
					"valid_from": {
						"type": "string",
						"title": "Valid From",
						"render": {
							"method": "input",
							"attributes": [
								{ "placeholder": "Enter valid from date" },
								{ "name": "valid_from" },
								{ "type": "datetime-local" }
							]
						}
					},
					"value": {
						"type": "number",
						"title": "Value",
						"render": {
							"method": "input",
							"attributes": [
								{ "placeholder": "Enter value" },
								{ "name": "value" },
								{ "type": "number" }
							]
						}
					}
				}
			}
		},

		"media": {
			"type": "array",
			"default": [],
			"title": "Media",
			"render": {
				"method": "media",
				"attributes": [
					{ "part": "media" }
				]
			},
			"items": {
				"type": "object",
				"required": [
					"media_id",
					"media_type",
					"url"
				],
				"properties": {
					"media_id": {
						"type": "integer",
						"property": "value",
						"render": {
							"method": "input",
							"attributes": [
								{ "name": "media" },
								{ "class": "bg-gray --fs-lg --cross" },
								{ "type": "checkbox" }
							]
						}
					},
					"media_type": {
						"type": "string"
					},
					"url": {
						"type": "string",
						"property": "src",
						"render": {
							"method": "img",

							"attributes": [
								{ "alt": "none" }
							]
						}
					}
				}
			}
		},
		"reviews": {
			"type": "array",
			"default": [],
			"title": "Reviews",
			"render": {
					"method": "grid",
					"attributes": [
						{ "part": "grid" }
					]
				},
			"items": {
				"type": "object",
				"title": "A Schema",
				"required": [
					"review_id",
					"reviewer",
					"review_date",
					"review_headline"
				],
				"properties": {
					"review_id": {
						"type": "integer",
						"title": "ID",
						"render": {
							"method": "input",
							"attributes": [
								{ "name": "review-id" },
								{ "type": "text" }
							]
						}
					},
					"reviewer": {
						"type": "string",
						"title": "Reviewer",
						"render": {
							"method": "input",
							"attributes": [
								{ "name": "reviewer" }
							]
						}
					},
					"review_date": {
						"type": "string",
						"title": "Date",
						"render": {
							"method": "input",
							"attributes": [
								{ "name": "review-date" },
								{ "type": "text" }
							]
						}
					},
					"review_headline": {
						"type": "string",
						"title": "Headline",
						"render": {
							"method": "input",
							"attributes": [
								{ "name": "review-headline" }
							]
						}
					}
				}
			}
		},

		"vendor": {
			"type": "object",
			"default": {},
			"required": [
				"vendor_id",
				"vendor_name"
			],
			"properties": {
				"vendor_id": {
					"type": "integer",
					"render": {
						"method": "input",
						"attributes": [
							{ "placeholder": "Enter vendor ID" },
							{ "name": "vendor_id" },
							{ "type": "number" }
						]
					}
				},
				"vendor_name": {
					"type": "string",
					"render": {
						"method": "input",
						"attributes": [
							{ "placeholder": "Enter vendor name" },
							{ "name": "vendor_name" },
							{ "type": "text" }
						]
					}
				}
			}
		},
		"channels": {
			"type": "array",
			"default": [],
			"render": {
				"method": "renderChannels"
			},
			"items": {
				"type": "object",
				"required": [
					"channel_name",
					"expected_delivery",
					"quantity_in_stock"
				],
				"properties": {
					"channel_name": {
						"type": "string",
						"title": "Channel Name",
						"render": {
							"method": "input",
							"attributes": [
								{ "placeholder": "Enter channel name" },
								{ "name": "channel_name" },
								{ "type": "text" }
							]
						}
					},
					"expected_delivery": {
						"type": "string",
						"title": "Expected Delivery",
						"render": {
							"method": "input",
							"attributes": [
								{ "placeholder": "Enter expected delivery date" },
								{ "name": "expected_delivery" },
								{ "type": "datetime-local" }
							]
						}
					},
					"quantity_in_stock": {
						"type": "integer",
						"title": "Quantity in Stock",
						"render": {
							"method": "input",
							"attributes": [
								{ "placeholder": "Enter quantity in stock" },
								{ "name": "quantity_in_stock" },
								{ "type": "number" }
							]
						}
					}
				}
			}
		}
	}
}

=== AimWhy/browser-style/ui/data-entry/assets/product.json
{
  "id": 190155,
  "name": "Foundation",
  "description": "For twelve thousand years the <b>Galactic Empire</b> has ruled supreme. Now it is dying. But only <i>Hari Seldon</i>, creator of the revolutionary science of psychohistory, can see into the future — to a dark age of ignorance, barbarism, and warfare that will last thirty thousand years. To preserve knowledge and save humankind, Seldon gathers the best minds in the Empire — both scientists and scholars — and brings them to a bleak planet at the edge of the galaxy to serve as a beacon of hope for future generations. He calls his sanctuary the <b>Foundation</b>.",
  "product_type_id": 1,
  "condition": 1,
  "published": false,
  "searchable": true,
  "sku": "172137",
  "created_at": "2022-08-11T00:00:00",
  "last_modified_at": "2024-05-22T13:26:16",
  "attributes": [
    {
      "attr_label": "Isaac Asimov",
      "attr_type": "Book Author",
      "attr_value": 1
    },
    {
      "attr_label": "Foundation",
      "attr_type": "Book Series",
      "attr_value": 2
    },
    {
      "attr_label": "Science Fiction",
      "attr_type": "Book Genre",
      "attr_value": 3
    }
  ],
  "price": [
    {
      "price_id": 359414,
      "currency_code": "USD",
      "discount": false,
      "is_msrp": true,
      "valid_from": "2024-05-22T13:26:24",
      "value": 19.95
    },
    {
      "price_id": 359415,
      "currency_code": "DKK",
      "discount": false,
      "is_msrp": true,
      "valid_from": "2024-04-22T13:26:24",
      "value": 199.50
    }
  ],
  "vendor": {
    "vendor_id": 1007,
    "vendor_name": "Penguin Random House"
  },
  "channels": [
    {
      "channel_name": "Default",
      "expected_delivery": "2004-11-30T14:17:24",
      "quantity_in_stock": 1
    }
  ],
  "media": [
    {
      "media_id": 190155,
      "media_type": "image",
      "url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1417900846i/29579.jpg"
    },
    {
      "media_id": 190156,
      "media_type": "image",
      "url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1558401363i/40793127.jpg"
    },
    {
      "media_id": 190157,
      "media_type": "image",
      "url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1629666224i/58831139.jpg"
    }
  ],
  "reviews": [
    {
      "review_id": 190155,
      "reviewer": "John Doe",
      "review_date": "2024-05-22T13:26:24",
      "review_headline": "This is a great book!"
    },
    {
      "review_id": 190156,
      "reviewer": "Jane Doe",
      "review_date": "2024-05-22T13:26:24",
      "review_headline": "I love this book!"
    }
  ]
}
